export const Actions = {
  HTTP_BRIDGE_APP: 'HTTP_BRIDGE_APP',
  HTTP_BRIDGE_CREATED: 'HTTP_BRIDGE_CREATED',
  HTTP_BRIDGE_REQUEST: 'HTTP_BRIDGE_REQUEST',
  HTTP_BRIDGE_REQUEST_CANCEL: 'HTTP_BRIDGE_REQUEST_CANCEL',
  HTTP_BRIDGE_RESPONSE_DATA: 'HTTP_BRIDGE_RESPONSE_DATA',
  HTTP_BRIDGE_RESPONSE_END: 'HTTP_BRIDGE_RESPONSE_END',
  HTTP_BRIDGE_RESPONSE_ERROR: 'HTTP_BRIDGE_RESPONSE_ERROR',
  HTTP_BRIDGE_RESPONSE_HEADERS: 'HTTP_BRIDGE_RESPONSE_HEADERS',
  SERVER_LISTENING: 'SERVER_LISTENING',
  SOCKET_CONNECTED: 'SOCKET_CONNECTED',
  SOCKET_DISCONNECTED: 'SOCKET_DISCONNECTED',
}
